[package]
name = "rampart-desktop"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
engine-greywall = { path = "../../../crates/engine-greywall" }
engine-windows = { path = "../../../crates/engine-windows" }
rampartd = { path = "../../../crates/rampartd" }
policy-core = { path = "../../../crates/policy-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2", features = [] }
